### ISSUE TITLE
Documentation for BackgroundGeolocation class on Android

### ISSUE THREAD

**Issue by mobiRic** [transistorsoft/background-geolocation-lt#32]
Is there (javadoc?) documentation on the methods of the `BackgroundGeolocation` class?

I am using the plugin as an Android native java developer, in a project that will sometimes not be run with any UI (similar in a way to the headless JS use cases).

Of specific interest at the moment is the `Intent` that the library can be initialised with, or that can be passed in `setIntent()`; and the use of `isDead()`.

## Your Environment
* Plugin version: 2.14.2
* Platform: Android
* OS version: all
* Device manufacturer / model: all
* Plugin config: without UI

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
The only docs available are [here](https://github.com/transistorsoft/background-geolocation-lt/tree/master/docs)

>Of specific interest at the moment is the Intent that the library can be initialised with

You should provide the SDK with the `Intent` delivered to your `MainActivity`.  The only reason the plugin needs the `Intent` is so it can determine if the `MainActivity` was *force-launched* due to using the SDK's `forceReloadOnXXX` configuration options.  In that case, the plugin will have created its own `Intent` with some added `extras`.  If you're not using these options at all, it doesn't matter what `Intent` you send.  You can even provide *no Intent* in that case or simply a `new Intent()`.

> and the use of isDead().

You are not meant to use `isDead`.

**Comment by mobiRic** [comment]
Thanks, Chris,

Regarding the terminology used in the _force-launched_ documentation, when it says "Launch your app whenever the <insert event name> event fires" does that refer (in native Android terms) to the `MainActivity` resuming and becoming visible? (assuming these docs seem to be aimed mostly at the JS developers where the app mostly "lives" inside an `Activity`)

**Comment by christocracy** [comment]
>when it says "Launch your app whenever the event fires" does that refer (in native Android terms) to the MainActivity

Correct.  Yes, these docs were initially written to target Cordova users.

Native developers should have no need for force-launching the `MainActivity`.
